name: moteis
description: "A simple app to list motels"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  json_serializable: ^6.9.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
